async def check_slots(date: str, service: str) -> list[dict]: ...
async def book_appointment(lead_id: str, slot_iso: str, service: str) -> dict: ...
async def transfer_to_human(reason: str) -> dict: ...
async def send_whatsapp(lead_id: str, template: str, params: dict) -> dict: ...
async def mark_dnd(lead_id: str, reason: str) -> dict: ...